name: AirAsia docker test pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run AirAsia sample E2E tests in a docker container
      run: |
        docker-compose up -d selenium-hub chrome firefox
        docker-compose up search-module
        docker-compose down
